- README.md
I just put my second surname (for those who don't know in spain we have two surnames) in the README.md
> Fixing name

- state.py
State class and a save parser, will have save done soon!
> State class with save parser

- Puzzle.py
Class still needs work to include things from the DataSource file so that it will actually have a wordList to look at and work off of.
May need some changing so that the file doesn't always have to query for the entire dictionary. Detailed on line 57
> Addition of the Puzzle class for generating puzzle

- Puzzle.py
I changed all the class variables to be available to anyone by doing Puzzle.varName, alternatively you can use the getter and setter methods in whatever way you choose.  This only allows for one possible puzzle at a time.
> Updated puzzle to remove objs

- Puzzle.py
All this change does is throw custom exceptions to be handled in the User interface class
> Puzzle except

- Puzzle.py
small fix sorry plz don't hate me
> fixing wordsList

- gameController.py
gmaeController class with guess and shuffle
> Game controller

- gameController.py
fix an error on the last possible guess edge case
> updated gameController to fix an error

- setup.py
works with dbCreator.py
makes env with pre-installed libraries
accessing env (Windows: spell/Scripts/Activate (Needs executionPolicy)) (Linux: source spell/bin/activate)
> Working Build system with functionality for windows/mac/linux

- BeeUI.py
> God please help me

- GameController.py
- main.py
> I didn't close the window

- BeeUI.py
- GameController.py
- SaveAndLoad.py
- TerminalInterface.py
- UserInterface.py
Changed save and load in BeeUI to use filedialog
BeeUI no longer needs to check for overwrite since filediag handles it
changed userinterface saveFileName function to take in an optional parameter for weather save or load is calling it
Changed terminal interface to "take" the type parameter for saveFileName and not use it for anything
Changed SaveAndLoad to check the saveName in functions that open or check files (isSaved, saveData, and load)
for / indicating a path name indicative of filediag from the GUI or no / indicative of saveName from CLI (don't know
if CLI allows for / in saveFile name)
filediag can save in any location the user wants and load from any location, restricted to json files only.
> Added functionality for save and load through file

- BeeUI.py
+ Ability to start a new game from the file menu anywhere
- Removed DEV controls
> File menu new

- SaveAndLoad.py
- TerminalInterface.py
saveFiles folder, added stuff to terminal interface to allow for the user to add their own path or default to cwd
> Changed save and load to default to cwd , and tweaked term interface

- README.md
made them easier to understand
> fixed spacing on test running commands

- .coveragerc
- UnitTests/test_SaveAndLoad.py
- pyproject.toml
- requirements.txt
- src/main.py
- src/test.py
Changed setup.py to a toml because original format is deprecated and toml has better usability for pytest and pip installs
moved main.py to src for entry point for build file
(Building/installing, pip install -e . (in root directory))
(Running program, Bee or Bee --cli)
(Running tests, pytest in env or pytest fileNames)
> setup.py -> pyproject.toml, main in src for entry

- src/view/BeeUI.py
This was a lot easier than I thought it would be.
- Updated wordfield in game to not be grayed out, but is still disabled from free typing.
- Updated the size of the new custom word box so it is in a larger font size.
> GUI wordfield update

- README.md
Added new installs pynput, setuptools, pytest-cov to required packages section
> Readme installs fix

- src/controller/GameController.py
- src/view/BeeUI.py
- src/view/TerminalInterface.py
- src/view/UserInterface.py
Adding cancel logic to the game:
- Explicit option on CLI
- X button on GUI
> Cancellogic

- README.md
- pyproject.toml
- src/controller/Context.py
- src/controller/GameController.py
- src/controller/SaveAndLoad.py
- src/controller/Strategy.py
- src/view/BeeUI.py
- src/view/TerminalInterface.py
> Encryp save and load

- src/view/BeeUI.py
- src/view/Inputer.py
- src/view/TerminalInterface.py
> hope this is my last commit
